#!/usr/bin/env python3
"""
FN:validate_markdown.py
Markdown Validation Script - Validates markdown files generated by web-to-markdown translator.

Classes:
- MarkdownValidator: Main validator class for checking markdown quality

Functions:
- FN:parse_args: Parse command line arguments (lines 140-165)
- FN:main: Entry point (lines 168-200)
"""

import argparse
import json
import logging
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class MarkdownValidator:
    """
    Validates markdown files for agent-friendly format compliance.
    
    Attributes:
        output_dir: Directory containing markdown files to validate
        errors: List of validation errors
        warnings: List of validation warnings
    """
    
    def __init__(self, output_dir: str):
        """FN:__init__ Initialize validator with output directory."""
        self.output_dir = Path(output_dir)
        self.errors: List[str] = []
        self.warnings: List[str] = []
        self.stats = {
            'total_files': 0,
            'files_with_frontmatter': 0,
            'files_with_headings': 0,
            'total_word_count': 0,
            'files_with_code_blocks': 0,
            'files_with_tables': 0
        }
    
    def validate_all(self) -> bool:
        """FN:validate_all Validate all markdown files in the output directory."""
        markdown_dir = self.output_dir / "markdown"
        
        if not markdown_dir.exists():
            self.errors.append(f"Markdown directory not found: {markdown_dir}")
            return False
        
        # Find all markdown files
        md_files = list(markdown_dir.rglob("*.md"))
        self.stats['total_files'] = len(md_files)
        
        logger.info(f"FN:validate_all Found {len(md_files)} markdown files")
        
        # Validate each file
        for md_file in md_files:
            self.validate_file(md_file)
        
        # Generate report
        self.generate_report()
        
        return len(self.errors) == 0
    
    def validate_file(self, file_path: Path) -> None:
        """FN:validate_file Validate a single markdown file."""
        logger.info(f"FN:validate_file Validating {file_path}")
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except Exception as e:
            self.errors.append(f"Failed to read {file_path}: {e}")
            return
        
        # Check frontmatter
        if not self._validate_frontmatter(content, file_path):
            self.errors.append(f"Missing or invalid frontmatter in {file_path}")
        else:
            self.stats['files_with_frontmatter'] += 1
        
        # Check headings
        if not self._validate_headings(content, file_path):
            self.warnings.append(f"No headings found in {file_path}")
        else:
            self.stats['files_with_headings'] += 1
        
        # Check word count
        word_count = self._count_words(content)
        self.stats['total_word_count'] += word_count
        
        if word_count < 50:
            self.warnings.append(f"Low word count ({word_count}) in {file_path}")
        
        # Check code blocks
        if self._has_code_blocks(content):
            self.stats['files_with_code_blocks'] += 1
        
        # Check tables
        if self._has_tables(content):
            self.stats['files_with_tables'] += 1
        
        # Check for broken links
        self._check_links(content, file_path)
    
    def _validate_frontmatter(self, content: str, file_path: Path) -> bool:
        """FN:_validate_frontmatter Check if frontmatter exists and is valid."""
        if not content.startswith('---'):
            return False
        
        # Extract frontmatter
        match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
        if not match:
            return False
        
        frontmatter = match.group(1)
        
        # Check required fields
        required_fields = ['source_url', 'title', 'crawled_at']
        for field in required_fields:
            if field not in frontmatter:
                self.warnings.append(f"Missing field '{field}' in frontmatter of {file_path}")
        
        return True
    
    def _validate_headings(self, content: str, file_path: Path) -> bool:
        """FN:_validate_headings Check if headings exist and follow hierarchy."""
        # Find all headings
        headings = re.findall(r'^(#{1,6})\s+(.+)$', content, re.MULTILINE)
        
        if not headings:
            return False
        
        # Check hierarchy (no skipped levels)
        prev_level = 0
        for level, text in headings:
            current_level = len(level)
            if current_level > prev_level + 1:
                self.warnings.append(
                    f"Skipped heading level in {file_path}: H{prev_level} -> H{current_level}"
                )
            prev_level = current_level
        
        return True
    
    def _count_words(self, content: str) -> int:
        """FN:_count_words Count words in markdown content."""
        # Remove frontmatter
        content = re.sub(r'^---.*?---\n', '', content, flags=re.DOTALL)
        # Remove code blocks
        content = re.sub(r'```.*?```', '', content, flags=re.DOTALL)
        # Count words
        return len(content.split())
    
    def _has_code_blocks(self, content: str) -> bool:
        """FN:_has_code_blocks Check if content has code blocks."""
        return bool(re.search(r'```', content))
    
    def _has_tables(self, content: str) -> bool:
        """FN:_has_tables Check if content has markdown tables."""
        return bool(re.search(r'\|\s*.+\s*\|', content))
    
    def _check_links(self, content: str, file_path: Path) -> None:
        """FN:_check_links Check for broken relative links."""
        # Find all markdown links
        links = re.findall(r'\[([^\]]+)\]\(([^\)]+)\)', content)
        
        for text, url in links:
            # Skip external links
            if url.startswith(('http://', 'https://', 'mailto:')):
                continue
            
            # Check if relative link exists
            if not url.startswith('#'):  # Skip anchor links
                linked_file = file_path.parent / url
                if not linked_file.exists():
                    self.warnings.append(
                        f"Broken link in {file_path}: [{text}]({url})"
                    )
    
    def generate_report(self) -> None:
        """FN:generate_report Generate validation report."""
        report_path = self.output_dir / "validation_report.json"
        
        report = {
            'status': 'PASS' if len(self.errors) == 0 else 'FAIL',
            'total_files': self.stats['total_files'],
            'total_word_count': self.stats['total_word_count'],
            'files_with_frontmatter': self.stats['files_with_frontmatter'],
            'files_with_headings': self.stats['files_with_headings'],
            'files_with_code_blocks': self.stats['files_with_code_blocks'],
            'files_with_tables': self.stats['files_with_tables'],
            'error_count': len(self.errors),
            'warning_count': len(self.warnings),
            'errors': self.errors,
            'warnings': self.warnings
        }
        
        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)
        
        logger.info(f"FN:generate_report Saved report to {report_path}")
        
        # Print summary
        print("\n" + "="*60)
        print("VALIDATION SUMMARY")
        print("="*60)
        print(f"Status: {'✅ PASS' if len(self.errors) == 0 else '❌ FAIL'}")
        print(f"Total Files: {self.stats['total_files']}")
        print(f"Total Words: {self.stats['total_word_count']}")
        print(f"Files with Frontmatter: {self.stats['files_with_frontmatter']}")
        print(f"Files with Headings: {self.stats['files_with_headings']}")
        print(f"Files with Code Blocks: {self.stats['files_with_code_blocks']}")
        print(f"Files with Tables: {self.stats['files_with_tables']}")
        print(f"Errors: {len(self.errors)}")
        print(f"Warnings: {len(self.warnings)}")
        print("="*60)
        
        if self.errors:
            print("\nERRORS:")
            for error in self.errors:
                print(f"  ❌ {error}")
        
        if self.warnings:
            print("\nWARNINGS:")
            for warning in self.warnings:
                print(f"  ⚠️ {warning}")


def parse_args() -> argparse.Namespace:
    """FN:parse_args Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Validate markdown files generated by web-to-markdown translator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  %(prog)s --output-dir ./web-content
  %(prog)s --output-dir ./knowledge-base
        '''
    )
    
    parser.add_argument(
        '--output-dir',
        required=True,
        help='Output directory containing markdown files'
    )
    
    return parser.parse_args()


def main() -> None:
    """FN:main Entry point for markdown validation."""
    args = parse_args()
    
    validator = MarkdownValidator(args.output_dir)
    success = validator.validate_all()
    
    # Exit with appropriate code
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
